Fix deduplicate rule test to use API-compliant window value
The API requires deduplicate window values to be multiples of 1000.
Changed from 86400 to 60000 milliseconds (60 seconds) to satisfy
the validation requirement.

Fixes: TestConnectionWithDeduplicateRule
Error: "window must be a multiple of 1000"